### ISSUE TITLE
replace requests with canvaspi

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/quiz-extension#1]
wherever possible replace requests with [canvasapi](http://canvasapi.readthedocs.io/)

**Comment by alisonmyers** [comment]
@JeremyH011 start here!

**Comment by JeremyH011** [comment]
I have a working prototype on this, but I do not have access to push it.

**Comment by JeremyH011** [comment]
All API requests that can be changed to canvasapi requests have been done so.
