### ISSUE TITLE
explain

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/quiz-extension#16]
Jeremy, can you explain this in extend_quiz.py? What is the imported value and why would it change? 

```
imported = 0

try:
	from helpers import create_instance, _get_course, _get_quiz, _get_students
	from util import shut_down
except:
	from src.helpers import create_instance, _get_course, _get_quiz, _get_students
	from src.util import shut_down, print_error
	imported = 1

FOLDER = os.path.abspath(os.getcwd())
if imported:
	INPUT = "{}/src/input".format(FOLDER)
	OUTPUT = "{}/src/output".format(FOLDER)
	LOGS = "{}/src/log".format(FOLDER)
else:
	INPUT = "{}/src/input".format(FOLDER)
	OUTPUT = "{}/src/output".format(FOLDER)
	LOGS = "{}/src/log".format(FOLDER)

if imported == 0:
	API_URL = "https://ubc.test.instructure.com/"
else:
	API_URL = input("Enter Canvas URL instance: ")
```

**Comment by JeremyH011** [comment]
Oh, I forgot the comment that section, I need to do that after.

But essentially 'imported' is just a flag for the compiler to deal with. Python deals with paths on a relative level (so, it depends on who calls the functions), so running the script from the Jupyter notebook file requires a different path than when running the script by itself. 

So everything under "if imported:" is for running the script from Jupyter notebook file, and anything under "else" is for running the script from the Python file directly (i.e. python extend_quiz.py from the console). I did this so it would be easier to debug in the future, as it allows us to test the Python file by itself without the Jupyter notebook.

**Comment by alisonmyers** [comment]
oh cool, just leave it, I'll add a comment (I like that it can run from both) 
I'll just update the API_URL part
