### ISSUE TITLE
add better error handling and interface notices

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/quiz-extension#3]
add more error checks for the user that include better interface notes (see [quiz-reports](https://github.com/saud-learning-services/quiz-reports/blob/master/src/interface.py)) for example

**Comment by JeremyH011** [comment]
Changed to better match other scripts currently in repo in prototype.
To be Added:
- Error Logging
- Specific Error code handling

**Comment by JeremyH011** [comment]
Print error and shut down features based on quiz-reports were added into pull request. In addition, error logging was added as well.
