### ISSUE TITLE
change input of extension info

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/quiz-extension#4]
input should be two files:
- 1: list of students with changes
- 2: list of quizzes to apply to 

- include template and error handling for reading csv

**Comment by JeremyH011** [comment]
Is there a particular reason we need to have inputs in 2 different files?
Current input has the following headers: course_id, quiz_id, student_number, extra_time

I feel this works easily enough. Some background on this issue would be helpful.

**Comment by alisonmyers** [comment]
The scenario is that a group of students will _always_ be given extra time for every (or almost every) assignment or quiz, I think it will be easier to manage having a single source for the student list and a separate source for the quiz list - so the instructor would only have 2 review 2 smaller files rather than review 1 potentially very large file (imagine 10 quizzes, 20 students per quiz)

**Comment by JeremyH011** [comment]
So we are assuming that the course stays the same in this case for all quizzes and students in this case then?

**Comment by alisonmyers** [comment]
yeah, this would work for one course at a time

**Comment by JeremyH011** [comment]
Got it. That makes a lot more sense now. Thank you. I will work to change it then.
